/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign4;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class WordStatisticsData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -65009929187166330L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WordStatisticsData\",\"namespace\":\"com.refactorlabs.cs378.assign4\",\"fields\":[{\"name\":\"count\",\"type\":\"long\"},{\"name\":\"ttcount\",\"type\":\"long\"},{\"name\":\"min\",\"type\":\"long\"},{\"name\":\"max\",\"type\":\"long\"},{\"name\":\"ssq\",\"type\":\"long\"},{\"name\":\"mean\",\"type\":\"double\"},{\"name\":\"var\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long count;
  @Deprecated public long ttcount;
  @Deprecated public long min;
  @Deprecated public long max;
  @Deprecated public long ssq;
  @Deprecated public double mean;
  @Deprecated public double var;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WordStatisticsData() {}

  /**
   * All-args constructor.
   * @param count The new value for count
   * @param ttcount The new value for ttcount
   * @param min The new value for min
   * @param max The new value for max
   * @param ssq The new value for ssq
   * @param mean The new value for mean
   * @param var The new value for var
   */
  public WordStatisticsData(java.lang.Long count, java.lang.Long ttcount, java.lang.Long min, java.lang.Long max, java.lang.Long ssq, java.lang.Double mean, java.lang.Double var) {
    this.count = count;
    this.ttcount = ttcount;
    this.min = min;
    this.max = max;
    this.ssq = ssq;
    this.mean = mean;
    this.var = var;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return count;
    case 1: return ttcount;
    case 2: return min;
    case 3: return max;
    case 4: return ssq;
    case 5: return mean;
    case 6: return var;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: count = (java.lang.Long)value$; break;
    case 1: ttcount = (java.lang.Long)value$; break;
    case 2: min = (java.lang.Long)value$; break;
    case 3: max = (java.lang.Long)value$; break;
    case 4: ssq = (java.lang.Long)value$; break;
    case 5: mean = (java.lang.Double)value$; break;
    case 6: var = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'count' field.
   * @return The value of the 'count' field.
   */
  public java.lang.Long getCount() {
    return count;
  }

  /**
   * Sets the value of the 'count' field.
   * @param value the value to set.
   */
  public void setCount(java.lang.Long value) {
    this.count = value;
  }

  /**
   * Gets the value of the 'ttcount' field.
   * @return The value of the 'ttcount' field.
   */
  public java.lang.Long getTtcount() {
    return ttcount;
  }

  /**
   * Sets the value of the 'ttcount' field.
   * @param value the value to set.
   */
  public void setTtcount(java.lang.Long value) {
    this.ttcount = value;
  }

  /**
   * Gets the value of the 'min' field.
   * @return The value of the 'min' field.
   */
  public java.lang.Long getMin() {
    return min;
  }

  /**
   * Sets the value of the 'min' field.
   * @param value the value to set.
   */
  public void setMin(java.lang.Long value) {
    this.min = value;
  }

  /**
   * Gets the value of the 'max' field.
   * @return The value of the 'max' field.
   */
  public java.lang.Long getMax() {
    return max;
  }

  /**
   * Sets the value of the 'max' field.
   * @param value the value to set.
   */
  public void setMax(java.lang.Long value) {
    this.max = value;
  }

  /**
   * Gets the value of the 'ssq' field.
   * @return The value of the 'ssq' field.
   */
  public java.lang.Long getSsq() {
    return ssq;
  }

  /**
   * Sets the value of the 'ssq' field.
   * @param value the value to set.
   */
  public void setSsq(java.lang.Long value) {
    this.ssq = value;
  }

  /**
   * Gets the value of the 'mean' field.
   * @return The value of the 'mean' field.
   */
  public java.lang.Double getMean() {
    return mean;
  }

  /**
   * Sets the value of the 'mean' field.
   * @param value the value to set.
   */
  public void setMean(java.lang.Double value) {
    this.mean = value;
  }

  /**
   * Gets the value of the 'var' field.
   * @return The value of the 'var' field.
   */
  public java.lang.Double getVar() {
    return var;
  }

  /**
   * Sets the value of the 'var' field.
   * @param value the value to set.
   */
  public void setVar(java.lang.Double value) {
    this.var = value;
  }

  /**
   * Creates a new WordStatisticsData RecordBuilder.
   * @return A new WordStatisticsData RecordBuilder
   */
  public static com.refactorlabs.cs378.assign4.WordStatisticsData.Builder newBuilder() {
    return new com.refactorlabs.cs378.assign4.WordStatisticsData.Builder();
  }

  /**
   * Creates a new WordStatisticsData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WordStatisticsData RecordBuilder
   */
  public static com.refactorlabs.cs378.assign4.WordStatisticsData.Builder newBuilder(com.refactorlabs.cs378.assign4.WordStatisticsData.Builder other) {
    return new com.refactorlabs.cs378.assign4.WordStatisticsData.Builder(other);
  }

  /**
   * Creates a new WordStatisticsData RecordBuilder by copying an existing WordStatisticsData instance.
   * @param other The existing instance to copy.
   * @return A new WordStatisticsData RecordBuilder
   */
  public static com.refactorlabs.cs378.assign4.WordStatisticsData.Builder newBuilder(com.refactorlabs.cs378.assign4.WordStatisticsData other) {
    return new com.refactorlabs.cs378.assign4.WordStatisticsData.Builder(other);
  }

  /**
   * RecordBuilder for WordStatisticsData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WordStatisticsData>
    implements org.apache.avro.data.RecordBuilder<WordStatisticsData> {

    private long count;
    private long ttcount;
    private long min;
    private long max;
    private long ssq;
    private double mean;
    private double var;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.refactorlabs.cs378.assign4.WordStatisticsData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.count)) {
        this.count = data().deepCopy(fields()[0].schema(), other.count);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ttcount)) {
        this.ttcount = data().deepCopy(fields()[1].schema(), other.ttcount);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.min)) {
        this.min = data().deepCopy(fields()[2].schema(), other.min);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.max)) {
        this.max = data().deepCopy(fields()[3].schema(), other.max);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ssq)) {
        this.ssq = data().deepCopy(fields()[4].schema(), other.ssq);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.mean)) {
        this.mean = data().deepCopy(fields()[5].schema(), other.mean);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.var)) {
        this.var = data().deepCopy(fields()[6].schema(), other.var);
        fieldSetFlags()[6] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing WordStatisticsData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.refactorlabs.cs378.assign4.WordStatisticsData other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.count)) {
        this.count = data().deepCopy(fields()[0].schema(), other.count);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ttcount)) {
        this.ttcount = data().deepCopy(fields()[1].schema(), other.ttcount);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.min)) {
        this.min = data().deepCopy(fields()[2].schema(), other.min);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.max)) {
        this.max = data().deepCopy(fields()[3].schema(), other.max);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ssq)) {
        this.ssq = data().deepCopy(fields()[4].schema(), other.ssq);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.mean)) {
        this.mean = data().deepCopy(fields()[5].schema(), other.mean);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.var)) {
        this.var = data().deepCopy(fields()[6].schema(), other.var);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'count' field.
      * @return The value.
      */
    public java.lang.Long getCount() {
      return count;
    }

    /**
      * Sets the value of the 'count' field.
      * @param value The value of 'count'.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder setCount(long value) {
      validate(fields()[0], value);
      this.count = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'count' field has been set.
      * @return True if the 'count' field has been set, false otherwise.
      */
    public boolean hasCount() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'count' field.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder clearCount() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ttcount' field.
      * @return The value.
      */
    public java.lang.Long getTtcount() {
      return ttcount;
    }

    /**
      * Sets the value of the 'ttcount' field.
      * @param value The value of 'ttcount'.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder setTtcount(long value) {
      validate(fields()[1], value);
      this.ttcount = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ttcount' field has been set.
      * @return True if the 'ttcount' field has been set, false otherwise.
      */
    public boolean hasTtcount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ttcount' field.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder clearTtcount() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'min' field.
      * @return The value.
      */
    public java.lang.Long getMin() {
      return min;
    }

    /**
      * Sets the value of the 'min' field.
      * @param value The value of 'min'.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder setMin(long value) {
      validate(fields()[2], value);
      this.min = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'min' field has been set.
      * @return True if the 'min' field has been set, false otherwise.
      */
    public boolean hasMin() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'min' field.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder clearMin() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'max' field.
      * @return The value.
      */
    public java.lang.Long getMax() {
      return max;
    }

    /**
      * Sets the value of the 'max' field.
      * @param value The value of 'max'.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder setMax(long value) {
      validate(fields()[3], value);
      this.max = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'max' field has been set.
      * @return True if the 'max' field has been set, false otherwise.
      */
    public boolean hasMax() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'max' field.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder clearMax() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'ssq' field.
      * @return The value.
      */
    public java.lang.Long getSsq() {
      return ssq;
    }

    /**
      * Sets the value of the 'ssq' field.
      * @param value The value of 'ssq'.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder setSsq(long value) {
      validate(fields()[4], value);
      this.ssq = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'ssq' field has been set.
      * @return True if the 'ssq' field has been set, false otherwise.
      */
    public boolean hasSsq() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'ssq' field.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder clearSsq() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'mean' field.
      * @return The value.
      */
    public java.lang.Double getMean() {
      return mean;
    }

    /**
      * Sets the value of the 'mean' field.
      * @param value The value of 'mean'.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder setMean(double value) {
      validate(fields()[5], value);
      this.mean = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'mean' field has been set.
      * @return True if the 'mean' field has been set, false otherwise.
      */
    public boolean hasMean() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'mean' field.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder clearMean() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'var' field.
      * @return The value.
      */
    public java.lang.Double getVar() {
      return var;
    }

    /**
      * Sets the value of the 'var' field.
      * @param value The value of 'var'.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder setVar(double value) {
      validate(fields()[6], value);
      this.var = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'var' field has been set.
      * @return True if the 'var' field has been set, false otherwise.
      */
    public boolean hasVar() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'var' field.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder clearVar() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public WordStatisticsData build() {
      try {
        WordStatisticsData record = new WordStatisticsData();
        record.count = fieldSetFlags()[0] ? this.count : (java.lang.Long) defaultValue(fields()[0]);
        record.ttcount = fieldSetFlags()[1] ? this.ttcount : (java.lang.Long) defaultValue(fields()[1]);
        record.min = fieldSetFlags()[2] ? this.min : (java.lang.Long) defaultValue(fields()[2]);
        record.max = fieldSetFlags()[3] ? this.max : (java.lang.Long) defaultValue(fields()[3]);
        record.ssq = fieldSetFlags()[4] ? this.ssq : (java.lang.Long) defaultValue(fields()[4]);
        record.mean = fieldSetFlags()[5] ? this.mean : (java.lang.Double) defaultValue(fields()[5]);
        record.var = fieldSetFlags()[6] ? this.var : (java.lang.Double) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
