/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign6;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum BodyStyle {
  CONVERTIBLE, COUPE, HATCHBACK, MINIVAN, PICKUP, SUV959, SEDAN, VAN, WAGON, CHASSIS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"BodyStyle\",\"namespace\":\"com.refactorlabs.cs378.assign6\",\"symbols\":[\"CONVERTIBLE\",\"COUPE\",\"HATCHBACK\",\"MINIVAN\",\"PICKUP\",\"SUV959\",\"SEDAN\",\"VAN\",\"WAGON\",\"CHASSIS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
