/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign5;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum CabStyle {
  CREW_CAB, EXTENDED_CAB, REGULAR_CAB  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CabStyle\",\"namespace\":\"com.refactorlabs.cs378.assign5\",\"symbols\":[\"CREW_CAB\",\"EXTENDED_CAB\",\"REGULAR_CAB\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
